### ISSUE TITLE
yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead

### ISSUE THREAD

**Issue by monarchwadia** [jxson/front-matter#84]
Hi! Thank you for this amazing package. Maybe I doing something wrong here, or maybe this is a new bug because of versions, but reporting it here for y'all :-)

Was following the Remix tutorial [here](https://remix.run/docs/en/v1/tutorials/blog)  and my application blew up with the following error, originating from front-matter.

# Expected behaviour

Should parse frontmatter

# Actual behaviour

Blows up with an error.

```
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at /Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/node_modules/js-yaml/index.js:10:11
    at parse (/Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/node_modules/front-matter/index.js:64:20)
    at extractor (/Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/node_modules/front-matter/index.js:26:12)
    at /Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/app/post.ts:22:30
    at async Promise.all (index 1)
    at Object.callRouteLoader (/Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/node_modules/@remix-run/server-runtime/data.js:73:14)
```
![image](https://user-images.githubusercontent.com/4856944/155057586-bf3b4eed-1b7e-40ef-b09a-289df463fb21.png)

# Relevant files 

Here are the contents of `/Users/monarchwadia/Sandbox/2022-02-21-remix-run/action/app/post.ts:22:30` :

```
3      import parseFrontMatter from "front-matter";

// ...

22    const { attributes } = parseFrontMatter<Frontmatter>(file.toString());
```

My `md` files are the same ones from the tutorial.

# What I've tried

I tried `allowUnsafe: true` in the options object, and that worked as expected, probably because it uses `yaml.load()` under the hood.

But I'm not sure if this is wise. `allowUnsafe` is scary :-)

**Comment by monarchwadia** [comment]
Turns out to be a dependency conflict issue.  Some more info inside my `yarn.lock` helped me track this one down, possibly.

`@remix-run/dev` uses a library called `remark-mdx-frontmatter`
`remark-mdx-frontmatter` in turn uses `js-yaml "^4.0.0"`
Meanwhile, `front-matter` uses `js-yaml "^3.13.1"`

So clearly, `js-yaml` is being resolved at v4.0+

Closing this issue. Hopefully if someone comes across this in the future, they will know what caused it.
